/* Advanced frontend chat.js. Preserves the existing /api/chat streaming contract. */
(()=>{"use strict";
const C={apiEndpoint:"/api/chat",storageKey:"advanced-ai-chat-v1",themeKey:"advanced-ai-theme",maxChats:100,maxTitle:48,suggestions:["Explain something to me","Help me write something","Analyze this information","Help me solve a problem"]};
const S={chats:[],active:null,controller:null,generating:false,sidebar:false};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>`m_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
function md(src=""){let t=esc(src).replace(/\r\n?/g,"\n"),blocks=[],inline=[];
t=t.replace(/```([A-Za-z0-9_+-]*)\n?([\s\S]*?)```/g,(_,l,c)=>{let i=blocks.length;blocks.push({l:l||"text",c:c.replace(/\n$/,"")});return `\0C${i}\0`});
t=t.replace(/`([^`\n]+)`/g,(_,c)=>{let i=inline.length;inline.push(c);return `\0I${i}\0`});
t=t.replace(/\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g,(_,a,u)=>{try{let x=new URL(u);if(!/^https?:$/.test(x.protocol))return a;return `<a href="${esc(x.href)}" target="_blank" rel="noopener noreferrer">${a}</a>`}catch{return a}});
t=t.replace(/^###### (.+)$/gm,"<h6>$1</h6>").replace(/^##### (.+)$/gm,"<h5>$1</h5>").replace(/^#### (.+)$/gm,"<h4>$1</h4>").replace(/^### (.+)$/gm,"<h3>$1</h3>").replace(/^## (.+)$/gm,"<h2>$1</h2>").replace(/^# (.+)$/gm,"<h1>$1</h1>").replace(/^> ?(.+)$/gm,"<blockquote>$1</blockquote>");
t=t.replace(/(^|\n)((?:[-*+] .+(?:\n|$))+)/g,(_,a,b)=>a+"<ul>"+b.trim().split("\n").map(x=>`<li>${x.replace(/^[-*+] /,"")}</li>`).join("")+"</ul>");
t=t.replace(/(^|\n)((?:\d+\. .+(?:\n|$))+)/g,(_,a,b)=>a+"<ol>"+b.trim().split("\n").map(x=>`<li>${x.replace(/^\d+\. /,"")}</li>`).join("")+"</ol>");
let out=[],p=[];const flush=()=>{if(p.length){out.push("<p>"+p.join("<br>")+"</p>");p=[]}};
for(const l of t.split("\n")){if(!l.trim())flush();else if(/^<(h[1-6]|ul|ol|blockquote)/.test(l.trim())||/^\0C\d+\0$/.test(l.trim())){flush();out.push(l)}else p.push(l)}flush();
t=out.join("\n").replace(/\0I(\d+)\0/g,(_,i)=>`<code>${inline[+i]}</code>`).replace(/\0C(\d+)\0/g,(_,i)=>`<div class="code-wrap"><div class="code-head"><span>${esc(blocks[+i].l)}</span><button class="copy-code" type="button">Copy</button></div><pre><code>${esc(blocks[+i].c)}</code></pre></div>`);
return t.replace(/\*\*([^*\n]+)\*\*/g,"<strong>$1</strong>").replace(/__([^_\n]+)__/g,"<strong>$1</strong>").replace(/(^|[^\*])\*([^*\n]+)\*(?!\*)/g,"$1<em>$2</em>")||"<p></p>"}
function shell(){let r=$("#advanced-ai-chat")||document.body.appendChild(Object.assign(document.createElement("div"),{id:"advanced-ai-chat"}));r.innerHTML=`<div class="app-shell"><aside class="sidebar closed" id="ai-sidebar"><div class="brand"><div class="brand-mark">AI</div><span>AI Assistant</span><span class="brand-ai">Core</span><button class="icon-btn sidebar-close" id="sidebar-close">×</button></div><button class="new-chat" id="new-chat">＋ <span>New chat</span><kbd>Ctrl K</kbd></button><div class="side-search">⌕<input id="history-search" type="search" placeholder="Search conversations" aria-label="Search conversations"></div><div class="side-section" id="conversation-list"></div><div class="sidebar-bottom"><button class="bottom-item" id="theme-toggle">◐ <span>Theme</span></button><button class="bottom-item" id="clear-conversations">⌫ <span>Clear conversations</span></button></div></aside><div class="mobile-backdrop" id="sidebar-backdrop" hidden></div><main class="main"><header class="topbar"><button class="icon-btn" id="mobile-menu" aria-label="Open menu">☰</button><div class="model-select"><span class="model-dot"></span><span id="chat-title">New chat</span></div><div class="top-actions"><button class="icon-btn" id="header-new-chat" data-tooltip="New chat">＋</button><button class="icon-btn" id="header-theme" data-tooltip="Theme">◐</button></div></header><section class="chat-area" id="messages" aria-live="polite"><div class="messages" id="messages-inner"></div></section><div class="composer-wrap"><form class="composer" id="composer"><textarea id="message-input" rows="1" maxlength="20000" placeholder="Ask anything..." aria-label="Message"></textarea><button class="send-btn" id="send-btn" type="submit" disabled>↑</button></form><div class="composer-note">Enter to send · Shift + Enter for a new line</div></div></main></div>`}
function save(){try{localStorage.setItem(C.storageKey,JSON.stringify(S.chats.slice(0,C.maxChats)))}catch{}}
function load(){try{S.chats=JSON.parse(localStorage.getItem(C.storageKey)||"[]")}catch{S.chats=[]}setTheme(localStorage.getItem(C.themeKey)||"system");if(!S.chats.length)newChat(false);else S.active=S.chats[0].id}
function active(){return S.chats.find(x=>x.id===S.active)}
function newChat(persist=true){let c={id:uid(),title:"New chat",messages:[],updatedAt:Date.now()};S.chats.unshift(c);S.active=c.id;if(persist)save();render();closeSide();$("#message-input")?.focus()}
function title(c){let m=c.messages.find(x=>x.role==="user"&&x.content.trim());if(!m){c.title="New chat";return}c.title=m.content.replace(/```[\s\S]*?```/g,"").replace(/[*_`#>]/g,"").replace(/\s+/g," ").trim().slice(0,C.maxTitle)||"New chat"}
function renderSide(){let l=$("#conversation-list"),q=($("#history-search")?.value||"").toLowerCase();l.replaceChildren();let a=S.chats.filter(c=>!q||c.title.toLowerCase().includes(q));if(!a.length){l.innerHTML=`<div class="empty-history">No conversations found.</div>`;return}a.forEach(c=>{let b=document.createElement("button");b.className="history-item"+(c.id===S.active?" active":"");b.setAttribute("aria-current",c.id===S.active?"true":"false");b.innerHTML=`<span>${esc(c.title)}</span>`;b.onclick=()=>{if(!S.generating){S.active=c.id;render();closeSide()}};b.oncontextmenu=e=>{e.preventDefault();let x=prompt("Type rename or delete","rename");if(x==="rename")rename(c.id);if(x==="delete")del(c.id)};l.appendChild(b)})}
function rename(id){let c=S.chats.find(x=>x.id===id);if(!c)return;let x=prompt("Rename conversation",c.title);if(x!==null){c.title=x.trim().slice(0,C.maxTitle)||"New chat";save();render()}}
function del(id){let c=S.chats.find(x=>x.id===id);if(!c||!confirm(`Delete "${c.title}"?`))return;S.chats=S.chats.filter(x=>x.id!==id);if(!S.chats.length)newChat(false);else if(S.active===id)S.active=S.chats[0].id;save();render()}
function clearAll(){if(confirm("Delete all saved conversations? This cannot be undone.")){S.chats=[];newChat(false);save();render()}}
function welcome(){let w=document.createElement("div");w.className="welcome";w.innerHTML=`<div class="hero-orb">AI</div><p class="eyebrow">Intelligent interface</p><h1>How can I help?</h1><p class="subhead">Ask a question, create something, analyze information, or solve a difficult problem with your AI assistant.</p><div class="prompt-grid"></div>`;C.suggestions.forEach(x=>{let b=document.createElement("button");b.className="prompt-card";b.type="button";b.innerHTML=`<span class="prompt-icon">✦</span><span>${esc(x)}</span><span class="prompt-arrow">⌄</span>`;b.onclick=()=>{$("#message-input").value=x;resize();send()};$(".prompt-grid",w).appendChild(b)});return w}
function msg(m,i){let r=document.createElement("article");r.className=`message-row ${m.role==="user"?"user":"assistant"}`;r.dataset.index=i;r.innerHTML=`<div class="message-avatar">${m.role==="user"?"U":"✦"}</div><div class="message-body"><div class="message-name">${m.role==="user"?"You":"AI"}</div><div class="message-text">${m.pending?'<div class="typing"><i></i><i></i><i></i></div>':md(m.content||"")}</div>${m.error?`<div class="message-error">${esc(m.error)}</div>`:""}<div class="message-tools">${m.role==="assistant"&&!m.pending?'<button data-a="copy">Copy</button><button data-a="regen">Regenerate</button><button data-a="like">Like</button><button data-a="dislike">Dislike</button>':m.role==="user"?'<button data-a="edit">Edit</button>':""}</div></div>`;return r}
function renderMessages(){let x=$("#messages-inner"),c=active();x.replaceChildren();if(!c||!c.messages.length){x.appendChild(welcome());return}c.messages.forEach((m,i)=>x.appendChild(msg(m,i)));requestAnimationFrame(()=>{$("#messages").scrollTop=$("#messages").scrollHeight})}
function render(){renderSide();$("#chat-title").textContent=active()?.title||"New chat";renderMessages();update()}
function resize(){let x=$("#message-input");x.style.height="auto";x.style.height=Math.min(x.scrollHeight,140)+"px"}
function update(){let i=$("#message-input"),b=$("#send-btn");if(S.generating){b.disabled=false;b.textContent="■";b.setAttribute("aria-label","Stop generation")}else{b.textContent="↑";b.classList.toggle("ready",!!i.value.trim());b.disabled=!i.value.trim();b.setAttribute("aria-label","Send message")}}
function scroll(){let x=$("#messages");x.scrollTop=x.scrollHeight}
async function send(){if(S.generating){S.controller?.abort();return}let i=$("#message-input"),c=active(),text=i.value.trim();if(!c||!text)return;c.messages.push({role:"user",content:text,id:uid()});title(c);i.value="";resize();save();render();let a={role:"assistant",content:"",pending:true,id:uid()};c.messages.push(a);S.generating=true;S.controller=new AbortController();renderMessages();update();scroll();try{let r=await fetch(C.apiEndpoint,{method:"POST",headers:{"Content-Type":"application/json","Accept":"text/plain"},body:JSON.stringify({messages:c.messages.filter(m=>!m.pending&&!m.error).map(m=>({role:m.role,content:m.content}))}),signal:S.controller.signal});if(!r.ok||!r.body){let d=await r.text().catch(()=>""),e=r.status===429?"Too many requests right now. Please wait a moment and try again.":r.status>=500?"The AI service is temporarily unavailable. Please try again.":"Something went wrong. Please try again.";throw Error(e||d)}let reader=r.body.getReader(),dec=new TextDecoder();a.pending=false;for(;;){let{done,value}=await reader.read();if(done)break;a.content+=dec.decode(value,{stream:true});last();scroll()}a.content+=dec.decode();if(!a.content.trim())a.error="The AI returned an empty response. Please try again.";save();last()}catch(e){a.pending=false;if(e.name==="AbortError"){if(!a.content.trim())c.messages.pop();else a.content+="\n\n*Generation stopped.*"}else a.error=e.message||"Something went wrong. Please try again.";save();renderMessages()}finally{S.generating=false;S.controller=null;update();renderSide()}}
function last(){let c=active(),x=$("#messages-inner"),i=c.messages.length-1,m=c.messages[i],old=$$(".message-row",x)[i];if(m?.role!=="assistant")return;let n=msg(m,i);old?old.replaceWith(n):x.appendChild(n)}
async function copy(t,b){try{await navigator.clipboard.writeText(t);let o=b.textContent;b.textContent="Copied";setTimeout(()=>b.textContent=o,1100)}catch{prompt("Copy this text:",t)}}
function action(e){let b=e.target.closest("button");if(!b)return;if(b.classList.contains("copy-code")){copy(b.closest(".code-wrap").querySelector("code").textContent,b);return}let r=b.closest(".message-row"),c=active();if(!r||!c)return;let i=+r.dataset.index,m=c.messages[i],a=b.dataset.a;if(a==="copy")copy(m.content,b);if(a==="edit"){$("#message-input").value=m.content;c.messages=c.messages.slice(0,i);save();render();resize();$("#message-input").focus()}if(a==="regen"){let u=[...c.messages.slice(0,i)].reverse().find(x=>x.role==="user");if(u){c.messages=c.messages.slice(0,i);$("#message-input").value=u.content;resize();send()}}if(a==="like"||a==="dislike"){m.feedback=a;save();b.textContent=a==="like"?"Liked":"Disliked";setTimeout(()=>b.textContent=a==="like"?"Like":"Dislike",900)}}
function side(force){S.sidebar=typeof force==="boolean"?force:!S.sidebar;$("#ai-sidebar")?.classList.toggle("closed",!S.sidebar);let b=$("#sidebar-backdrop");b.hidden=!S.sidebar;$("#mobile-menu")?.setAttribute("aria-expanded",String(S.sidebar))}
function closeSide(){if(matchMedia("(max-width:720px)").matches)side(false)}
function setTheme(t){let actual=t==="system"?(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light"):t;document.documentElement.dataset.theme=actual;localStorage.setItem(C.themeKey,t)}
function toggleTheme(){let t=localStorage.getItem(C.themeKey)||"system";setTheme(t==="light"?"dark":t==="dark"?"system":"light")}
function init(){shell();load();$("#composer").onsubmit=e=>{e.preventDefault();send()};$("#message-input").oninput=()=>{resize();update()};$("#message-input").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.isComposing){e.preventDefault();if(!S.generating)send()}};$("#messages-inner").onclick=action;$("#new-chat").onclick=()=>newChat();$("#header-new-chat").onclick=()=>newChat();$("#mobile-menu").onclick=()=>side();$("#sidebar-close").onclick=closeSide;$("#sidebar-backdrop").onclick=closeSide;$("#theme-toggle").onclick=toggleTheme;$("#header-theme").onclick=toggleTheme;$("#clear-conversations").onclick=clearAll;$("#history-search").oninput=renderSide;document.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();newChat()}if(e.key==="Escape")closeSide()};addEventListener("beforeunload",save);side(!matchMedia("(max-width:720px)").matches);render()}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init,{once:true}):init();
})();